version: '3.8'

services:
  grafana-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GRAFANA_URL=${GRAFANA_URL}
      - GRAFANA_USERNAME=${GRAFANA_USERNAME}
      - GRAFANA_PASSWORD=${GRAFANA_PASSWORD}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DEBUG_LOGGING=${DEBUG_LOGGING:-false}
    restart: unless-stopped
    # Uncomment the following lines if you want to use a .env file instead of environment variables
    # env_file:
    #   - .env